import { Amplify } from 'aws-amplify';
import { generateClient } from 'aws-amplify/data';
import type { Schema } from '../../amplify/data/resource';
import outputs from '../../amplify_outputs.json';

/**
 * `amplify_outputs.json` is generated by `npx ampx sandbox` (local dev) or by the
 * deployment pipeline. Until the backend is deployed it contains only a version
 * stamp, so we detect that and show setup instructions instead of crashing.
 */
const config = outputs as Record<string, unknown>;
export const isBackendConfigured = Boolean(
  (config as { auth?: { user_pool_id?: string } }).auth?.user_pool_id,
);

type DataOutputs = {
  api_key?: string;
  model_introspection?: { queries?: Record<string, unknown> };
};

/** True when sandbox deployed the admin/bootstrap API (not a pre-admin amplify_outputs). */
export const isAdminBackendDeployed = Boolean(
  (config as { data?: DataOutputs }).data?.api_key &&
    (config as { data?: DataOutputs }).data?.model_introspection?.queries
      ?.bootstrapRequired,
);

if (isBackendConfigured) {
  Amplify.configure(config as Parameters<typeof Amplify.configure>[0]);
}

/** Strongly-typed AppSync GraphQL client (queries, mutations, subscriptions). */
export const client = generateClient<Schema>({
  authMode: 'userPool',
});

export type ConversationModel = Schema['Conversation']['type'];
export type MessageModel = Schema['Message']['type'];
export type UserProfileModel = Schema['UserProfile']['type'];
export type ConversationReadStateModel =
  Schema['ConversationReadState']['type'];
